helpers/utils.js, package.json
- mineBlock is a helper function that forces the test chain to mine a new block
=> add mineBlock function to helpers

contracts/standard/arbitration/ArbitratorCourt.sol, contracts/standard/proxy/ArbitratorVersioningProxy.sol, contracts/standard/proxy/ExperimentalProxy.sol, contracts/standard/proxy/Proxy.sol
When this PR is approved, I can make a `KlerosPOCCourt` that extends `ArbitratorCourt` in kleros/kleros.
=> feat(arbitration): implement arbitrator subcourts

contracts/standard/arbitration/ArbitratorCourt.sol, contracts/standard/proxy/ArbitratorVersioningProxy.sol
=> feat(arbitrator-court): local arbitrator court appeals

contracts/standard/permission/AddressBlacklist.sol, contracts/standard/permission/AddressPermissionInterface.sol, contracts/standard/permission/AddressWhitelist.sol, contracts/standard/permission/Blacklist.sol, contracts/standard/permission/Whitelist.sol
The same bug and the same fix as in #41
=> Fixed missing view declaration

contracts/standard/permission/ArbitrableBlacklist.sol
After the if-else block, at line 173, we have that statement anyway.
=> Deleted duplicate statement `item.lastAction=now`

contracts/standard/arbitration/ArbitrableDeposit.sol
Hello!
This is my attempt at issue #38. Let me know if my implementation is at all wrong.
=> Address issue #38: Make general arbitrable deposit contract

package.json
4.1.12 is the first version supports new constructor() declaration
=> Updates Truffle dependency version

.gitattributes
Please see https://github.com/kleros/kleros/pull/46
=> Solidity syntax highlighting

README.md
* Added "We follow [GitHub Flow](https://guides.github.com/introduction/flow/) in this repository."
* Minor rewording in contributing section
=> Added git workflow line

contracts/standard/arbitration/ArbitratorCourt.sol
Removed `maxLocalAppeals` from `ArbitratorCourt`.
=> Refactor: Remove maxLocalAppeals from ArbitratorCourt

contracts/standard/arbitration/ArbitrableDeposit.sol
I used `send` instead `transfer` because with remix ide I have this tricky error: `the constructor must payable` but with `send` it works fine
=> [FIX & CS] make deposit fn payable

test/blockhashRNG.js, test/blockhashRNGFallback.js
Added tests for blockHashRNG and blockHashRNGFallbck as per issue #85
=> Added tests for blockhashRNG and blockhashRNGFallbck

test/arbitrablePermissionList.js
Fixes #83 
Sorry for linter diffs. File got so big, so I started to use linter to format it. We should standardize it with Solium I think by adding solium configuration files in the repo.
I made changes mainly in "When item in submitted state" case because `rechallengePossible` changes behaviour of only when in submitted state.
To not to duplicate all of the test cases I put `if(!rechallengePossible)` condition for other item states. Because those test cases are independent from the value of `rechallengePossible`.
=> Test: Add rechallengePossible case

.soliumignore, .soliumrc.json
Added initial Solium config files.
As an initial configuration I used [`solium-all` ruleset](https://github.com/duaraghav8/Solium/blob/master/config/rulesets/solium-all.js).
=> Style: Add initial config of Solium

.travis.yml, package-lock.json, package.json, scripts/coverage.sh, scripts/test.sh
Addressing #94 partially.
Tests working. Linting and code coverage to do.
This is the build result of my fork: https://travis-ci.org/ferittuncer/kleros-interaction/builds/413549249
=> Initial Travis configuration

package.json
to update the new contracts on the npm package store
=> [chore] update npm version

test/arbitrablePermissionList.js
I added some variables in construction test which were not checked previously. Did some cleanup on variable declarations and deleted leftover comments.
=> Test: Minor improvements and cleanup

contracts/standard/arbitration/CentralizedCourt.sol
An implementation of a centralised court, in the proposed standard ERC792. Resolves issue #17.
=> Created CentralisedCourt.sol

contracts/standard/rng/BlockhashRNG.sol, contracts/standard/rng/BlockhashRNGFallback.sol
1. Eliminate redundancy in BlockHashRNGFallback by abstracting fallback strategy out of saveRN().
2. Change fallback algorithm as per https://github.com/kleros/kleros-interaction/issues/105 .
=> Refactor blockhash random generator

package.json
https://www.npmjs.com/package/kleros-interaction
=> fix: wrong package number

contracts/standard/arbitration/MultipleArbitrableTransaction.sol, test/multipleArbitrableTransaction.js, yarn.lock
- `_transactionId` ->  `_metaEvidenceID` so that contract follows the standard
=> fix: make mult arbitrable evidence standard compliant

test/arbitrable-kitty.js
=> Fix anoying issue #121 causing tests to occasionally fail

package.json
at this time the abi multipleArbitrablePayment is broken with the solidity contract
I published a new version on the `npm` store
=> chore(abi): update abi smart contract

contracts/standard/arbitration/MultipleArbitrableTransaction.sol, test/multiple-arbitrable-transaction.js
see https://github.com/kleros/kleros-interaction/pull/150
=> fix(multiple-arbitrable-payment): handle no ruling

contracts/standard/arbitration/AppealableArbitrator.sol
Avoid arbitrator to change ruling after ruling deadline. Fixes #147 .
=> fix(ruling): avoid arbitrator to change ruling

contracts/standard/permission/ArbitrableTokenList.sol, test/arbitrable-token-list.js
Changes:
- Favor loser if winner doesn't pay appeal fees
- Add more comments
- Change "EXECUTE" to "ACCEPT" to be more descriptive
=> [WIP] - Implement suggestions from review

contracts/standard/arbitration/MultipleArbitrableTransaction.sol
and remove the restriction to call the timeout (@mtsalenc proposal)
=> chore(multiple-arbitrable-transaction): set RAB pragma comment

contracts/standard/arbitration/MultipleArbitrableTransaction.sol
See https://docs.google.com/document/d/1QmGVW2ZNT5Am4VEn-yNY4pniDEJ2JNc0bTOl3bLjMLA/edit#
Fixes: 
* It’d be good to have a order of functions which makes sens
* Typo in comments “loosing”->”losing” 
* Typo “pay”->”paid to be” 
* Buyer and seller are switched in comments https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L149 and https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L124 
* Need doxygen @return comments https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTransaction.sol#L226 
* Need to start this comment with the name of the returned variable `countTransactions` …
=> fix(multiple-arbitrable-transaction): some fixes from Clement's review

contracts/standard/arbitration/MultipleArbitrableTransaction.sol
see https://docs.google.com/document/d/1-ejwQUkdShUkIIFkAs91A3dw6xviIsnRyJ8NaaeYWLs/edit#
=> feat(escrow): review 2

contracts/standard/arbitration/MultipleArbitrableTransaction.sol
See https://docs.google.com/document/d/1J_vyLSAVjoFGaIIUipdRO0RztTqvNcvifC8icX-of30/edit#
=> refactor(escrow): clement review

contracts/standard/permission/ArbitrableTokenList.sol, test/arbitrable-token-list.js
This updates the contract with 
- Latest [research insights](https://github.com/kleros/research-docs/blob/master/klerosfees20dec2018.pdf)
- Feedback from latest reviews at #158
=> Update T2CR contract

contracts/standard/permission/ArbitrableTokenList.sol, test/arbitrable-token-list.js
Include a mapping of token address to submissions to allow querying by address.
=> Feat: Address query

contracts/standard/permission/ArbitrableAddressList.sol, contracts/standard/permission/ArbitrableTokenList.sol, test/arbitrable-address-list.js, test/arbitrable-token-list.js
This pull request will concentrate any changes to the ArbitrableTokenList and ArbitrableAddressList contracts.
=> feat: Update ArbitrableTokenList and ArbitrableAddressList

contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol, test/multiple-arbitrable-token-transaction.js
see https://docs.google.com/document/d/15rgNrGiBNsWMlrdXqfIka7jRJXztBiAyUv1yzP1qQ7Y/edit#
=> fix(escrow): @clesaege review and hotfixes

contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol, contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Index _transactionID and _party in Payment event.
=> feat(multiple-arbitrable-transactions): index payment event

contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
I found no issues with the smart contract. This PR only includes some suggestions for styling and docs.
=> Review by Matheus

contracts/standard/arbitration/Esperanto.sol, test/esperanto.js
@unknownunknown1 
```
Meta-evidence JSON:
{
"fileURI": string,
"category": "Translation",
"title": taskTitle,
"description": "This is a translation task ..."
}
and `fileURI` links to a JSON:
{
"text": "some text to be translated",
"sourceText": "context text",
"sourceLanguage": "English",
"targetLanguage": "Turkish",
"quality": "Perfect"
}
```
=> refactor(esperanto): remove some fields from Task struct

contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
- Make contract variables readable
=> fix(MultipleArbitrableTokenTransaction): make contract variables public

test/esperanto.js
This was the change I was talking about @unknownunknown1
=> test(esperanto): cleaner comparison

test/linguo.js
Added regression test for Linguo contract to ensure task price and required deposit are correctly calculated when the task status is not `created`.
=> Test(Linguo): added regression test

contracts/standard/arbitration/MultipleArbitrableTransactionWithFee.sol, test/multiple-arbitrable-transaction-with-fee.js
=> Adding Kleros Escrow ETH Version with Fee Recipient

contracts/standard/arbitration/MultipleArbitrableTokenTransactionWithFee.sol, contracts/standard/arbitration/MultipleArbitrableTransactionWithFee.sol, test/multiple-arbitrable-token-transaction-with-fee.js, test/multiple-arbitrable-transaction-with-fee.js
=> Adding/Updating Kleros Escrow Fee Recipient Versions

contracts/standard/proxy/RealitioArbitratorProxy.sol
=> Updated Bounty Details of RAB Pragma in Realitio Arbitrator Proxy
