- contracts/standard/arbitration/ArbitrableTokens/MiniMeTokenERC20.sol
`approve` function in MiniMeTokenERC20 successfully removes forcing current allowance to be 0, but also removes actual approval, this PR fixes that.
> Make approve in MiniMeTokenERC20 actually approve

- contracts/standard/arbitration/ArbitrableTokens/MiniMeTokenERC20.sol
Currently `MiniMeTokenERC20` doesn't implement any constructor and doesn't pass arguments to base constructor, making it abstract and rendering any attempts to deploy it fail.
This PR adds constructor calling base constructor with all supplied arguments, so it can actually be used.
> Add constructor to MiniMeTokenERC20

- contracts/standard/rng/BlockhashRNGFallback.sol
**Steps to reproduce:**
`cd kleros-interaction`
`truffle test`
**Output:**
<pre>Using network 'development'.
Error: Could not find /home/u/Repos/kleros-interaction/contracts/standard/rng/BlockHashRNG.sol from any sources; imported from /home/u/Repos/kleros-interaction/contracts/standard/rng/BlockhashRNGFallback.sol
at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:76:1
at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
at next (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/whilst.js:68:1)
at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:64:1
at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:85:1
at …
> Fixes Typo in Import Statement Which Causes Compilation Error

- contracts/standard/permission/ArbitrableBlacklist.sol
`ArbitrableBlacklist` constructor was called erroneously. Base constructor `Arbitrable` needs `address arbitrator`, `bytes arbitratorExtraData` and `bytes32 contractHash` which was missing.
> Added Missing Arguments to Base Constructor in ArbitrableBlacklist

- contracts/standard/permission/ArbitrableBlacklist.sol
- contracts/standard/permission/PermissionInterface.sol
**Bug:** In `ArbitrableBlacklist` contract `function isPermitted(bytes32 _value) public returns (bool allowed)` is a view function (does not change the state) but missing `view` declaration. This causes the `isPermitted` to return a transaction result instead of `bool`.
**Fix:** Just added `view` declaration to `PermissionInterface.isPermitted` (where `isPermitted` was inherited from) and `ArbitrableBlacklist.isPermitted`.
> Fixed isPermitted by adding missing view declaration

- contracts/standard/permission/ArbitrableBlacklist.sol
Added `function getItem(bytes32 key) public view returns(ItemStatus status, uint lastAction, address submitter, address challenger, uint balance, bool disputed, uint disputeID)` to `ArbitrableBlacklist` contract to be able to retrieve `Item` values from `items` map. This is necessary for testing `ArbitrableBlacklist` from Javascript as there is no other way to reach `Item` values (or I'm not aware).
> Added getItem view function

- contracts/Migrations.sol
- contracts/standard/arbitration/AppealableArbitrator.sol
- contracts/standard/arbitration/Arbitrable.sol
- contracts/standard/arbitration/ArbitrableDeposit.sol
- contracts/standard/arbitration/ArbitrableTokens/FundingVault.sol
- contracts/standard/arbitration/ArbitrableTokens/LockedToken.sol
- contracts/standard/arbitration/ArbitrableTokens/MiniMeTokenERC20.sol
- contracts/standard/arbitration/ArbitrableTransaction.sol
- contracts/standard/arbitration/Arbitrator.sol
- contracts/standard/arbitration/ArbitratorCourt.sol
- contracts/standard/arbitration/BackupedArbitrator.sol
- contracts/standard/arbitration/BountyVault.sol
- contracts/standard/arbitration/CentralizedArbitrator.sol
- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
- contracts/standard/arbitration/Rental.sol
- contracts/standard/arbitration/TwoPartyArbitrable.sol
- contracts/standard/permission/AddressPermissionList.sol
- contracts/standard/permission/ArbitrableBlacklist.sol
- contracts/standard/permission/ArbitrablePermissionList.sol
- contracts/standard/permission/PermissionList.sol
- contracts/standard/proxy/ArbitratorVersioningProxy.sol
- contracts/standard/proxy/ExperimentalProxy.sol
- contracts/standard/proxy/VersioningProxy.sol
- contracts/standard/rng/BlockhashRNG.sol
- contracts/standard/rng/BlockhashRNGFallback.sol
- contracts/standard/rng/ConstantNG.sol
- contracts/standard/rng/RNG.sol
> Eliminating Some Compiler Warnings

- contracts/standard/arbitration/Arbitrable.sol
- contracts/standard/arbitration/ArbitrableDeposit.sol
- contracts/standard/arbitration/ArbitrableTokens/FundingVault.sol
- contracts/standard/arbitration/ArbitrableTransaction.sol
- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
- contracts/standard/arbitration/Rental.sol
- contracts/standard/arbitration/TwoPartyArbitrable.sol
- contracts/standard/permission/ArbitrableBlacklist.sol
- contracts/standard/permission/ArbitrablePermissionList.sol
- package.json
- test/arbitrableBlacklist.js
- test/arbitrableTransaction.js
- test/multipleArbitrableTransaction.js
- test/twoPartyArbitrable.js
- Add MetaEvidence events to `Arbitrable.sol`
- `TwoPartyArbitrable.sol` takes metaEvidence as a argument and emits events
> feat: add MetaEvidence events

- contracts/standard/permission/ArbitrablePermissionList.sol
The new `blacklist` and `appendOnly` are the only setting variables which are not public. Is there a reason?
One reason to make them public is testability. While testing, I realized that I can't access them. 
Setting them public only gives read access by auto-generated getters, so it should be safe.
> refactor: change visibility of blacklist and appendOnly to public

- contracts/standard/permission/ArbitrablePermissionList.sol
- test/arbitrablePermissionList.js
- The logic in `isPermitted` was flipped. A blacklist contract should return true for everything not on the list and false for everything submitted or registered.
- Some naming changes. We can take or leave these changes. I just made a PR for easier discussion.
> isPermitted logic was flipped. Renaming function

- package.json
Replaced with zeppelin-solidity with openzeppelin-solidity.
See: https://www.npmjs.com/package/zeppelin-solidity
> Chore: Replace deprecated package

- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Add a getter to know the count of transaction. 
It's a helper for the store to associate data of the arbitrable transaction (metaEvidence, email) with the address of the smart contract (because we can have different address of multipleArbitration even if it's not a very good idea except if it's for different network) and the index of the arbitrable transaction.
> [feat] getter to count transactions

- contracts/standard/arbitration/SimpleTwoPartyArbitrableEscrowPayment.sol
- test/arbitrable-kitty.js
Fixs:
- comment arbitrableKitty test to can make a PR with the flag `no-verify` see https://github.com/kleros/kleros-interaction/issues/121
- conflict name on twoArbitrablePayment contracts
> fix bad reference to the smart contract / arbitrableKitty test

- contracts/standard/permission/ArbitrableTokenList.sol
- test/arbitrable-token-list.js
The previous version of queryItems() did not allow certain combinations of filter parameters such as querying undisputed registration requests and disputed preventive clearing requests.
This pull request adds more options for filters and documentation for each element of the filter array.
> fix: Upgrade queryItems()

- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
- test/multiple-arbitrable-transaction.js
- Keep track of `arbitrationCost` for more accurate fee refunds.
- Prevent overflow on timeout require statements.
- Disallow paying fees if dispute created. 
- Disallow calling rule if dispute as been resolved.
- Refund overpaid arbitration fees to the correct parties.
> fix: pre-review vulnerability fixes

- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
> fix(multiple-arbitrable-transaction): public vars

- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
> fix(multiple-arbitrable-transaction): fix incompatible events

- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
~Fix by modifying the require checks to make function revert if the party already paid arbitration fees.~
Fix by changing statement orders. Moved the call to `arbitrationCost` before require checks.
> fix(multiple-arbitrable-transaction): fix re-entrancy

- contracts/standard/permission/ArbitrableAddressList.sol
- contracts/standard/permission/ArbitrableTokenList.sol
- package.json
- test/arbitrable-address-list.js
- test/arbitrable-token-list.js
- truffle.js
This removes obsolete events and adds the following features:
- Allow submitting evidence when challenging a request;
- Emit WaitingOpponent whenever a party "passes" the adversary in arbitration fees. This way we can better notify when parties must fund their side to not lose due to being underfunded.
Additionally, this pull request also increases the gas limit of ganache to 8000000.
> Feat: Review Suggestions

- contracts/standard/arbitration/IArbitrable.sol
To avoid this warning: `@kleros/kleros-interaction/contracts/standard/arbitration/IArbitrable.sol:54:5: Warning: Functions in interfaces should be declared external.`
> fix:  functions in interfaces should be declared external

- contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
- test/multiple-arbitrable-token-transaction.js
- test/multiple-arbitrable-transaction.js
> feat(multiple-arbitrable): TransactionCreated event

- contracts/standard/arbitration/Linguo.sol
- test/linguo.js
Currently we don't have a timeline of the main events of the lifecycle of a translation task.
So far I identified the following use case:
- When displaying resolved tasks in the UI, we should sort them by descending completion date to give a feel of 'liveness'.
Another possibility would to display the task lifecycle in the UI or collecting metrics to perform data analysis like "how much time in average does it take to a task to be completed?"
This is an alternative to [#309](https://github.com/kleros/kleros-interaction/pull/309).
- Add a `TaskResolved` event to allow knowing when and why the task was marked as resolved.
- The reasons why a task might've been marked as resolved are:
1. The translation was accepted by the requester.
2. The requester was reimbursed either because no …
> Feat: added task lifecyle events to Linguo

- contracts/standard/arbitration/ArbitrableTokens/MiniMeTokenERC20.sol
RAB Pragma Added with the Author as @clesaege and reviewer as @remedcu
> RAB Pragma Added

- contracts/standard/rng/BlockhashRNG.sol
- contracts/standard/rng/BlockhashRNGFallback.sol
- contracts/standard/rng/RNG.sol
> Changes to RNG Folder

- contracts/standard/rng/BlockhashRNGFallbackRange.sol
Created a new RNG Generator with a Fallback using two of our previous smart contracts:
https://github.com/kleros/kleros-interaction/blob/6ec7f11/contracts/standard/rng/BlockhashRNGFallback.sol
https://github.com/kleros/kleros-interaction/blob/cf43218/contracts/standard/rng/BlockhashRNGFallback.sol
Instead of taking the previous hash like the latter one, we take any one of the last 256 block hashes of the mined blocks. But avoiding the former's vulnerability of allowing anyone to manipulate a `randomNumber` earlier than 256 blocks.
> Created BlockhashRNGFallbackRange.sol

- contracts/standard/arbitration/Arbitrable.sol
- contracts/standard/arbitration/Arbitrator.sol
- contracts/standard/arbitration/IArbitrable.sol
Task List:
- RAB Pragma Added
- Comment Updated
> RAB Pragma and Comment Updates to Arbitration Standard Contracts

- contracts/standard/arbitration/Linguo.sol
- test/linguo.js
Adding this method makes sense because it is symmetric to the `getDepositValue` method that already exists.
Beyond helping the UI to figure out the actual required deposit value for a challenge, this could be used as a guard check for other contracts willing to interact with Linguo.
> Linguo: added getChallengeValue method

- contracts/libraries/CappedMath.sol
> RAB Pragma of CappedMath Updated

- contracts/standard/arbitration/Linguo.sol
This PR makes no changes to logic, only comments and a variable name.
In addition, I'd like to propose the following change:
I believe the `challengeTranslation` should accept another parameter `string _evidence` to allow challenging and submitting an evidence at the same time.
On the T2CR there were cases where the challenger would delay submitting the justification as much  as possible, to make it difficult for the defendant to make a proper response in a timely manner. With this additional field we can require at the policy level that the challenger provide at least a basic summary of the accusation in order to not lose the case.
> review: Matt's linguo review

- contracts/standard/arbitration/Linguo.sol
- contracts/standard/arbitration/LinguoToken.sol
- contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
- contracts/standard/arbitration/MultipleArbitrableTokenTransactionWithFee.sol
- contracts/standard/arbitration/MultipleArbitrableTransaction.sol
- contracts/standard/arbitration/MultipleArbitrableTransactionWithFee.sol
- contracts/standard/proxy/RealitioArbitratorProxy.sol
> Updated: RAB Pragma of Linguo & Escrow | Comment updated in Escrow with Fee

- contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
- contracts/standard/arbitration/MultipleArbitrableTokenTransactionWithFee.sol
Reason:
The mutex was initially added as a reentrance guard. But as the `transaction.amount` was updated before the token transaction, this does not help much.
> Token Transaction Mutex Removed & Comment Updated

- contracts/standard/rng/ChainlinkRNG.sol
- package.json
- yarn.lock
Changes after @unknownunknown1 and @shalzz reviews
> feat: update chainlink version and remove RNG

- contracts/standard/rng/BeaconRNGFallback.sol
Addition of abstract function from RNG.sol into BeaconRNGFallback.sol
> fix: missing contribute function
